---
title: "How to start"
author: "Aparicio Johan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to start}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#"
)
```

## Loading libraries

```{r setup, warning=F,message=F}
library(tidyverse)
library(GS)
library(sommer)
```


## Genotypic information

```{r, warning=F,message=F}
data(DT_cpdata)

geno <- GT_cpdata
geno[1:5,1:3]
```

## Vector with genotype names
```{r, warning=F,message=F}
samp <- rownames(GT_cpdata)
samp[1:5]
```

## Phenotypic information
```{r, warning=F,message=F}
phen <- DT_cpdata
head(phen,3)
```


## Cross validation
```{r, warning=F, message=F}
tmp <- crossGP(geno,samp,phen,prior = "sommer", niter=20,testporc = 0.3,traits = names(phen)[c(5,7)])
```

## plot

```{r}
ggplot(tmp$data, aes(x=trait,y=corr, fill=trait))+geom_boxplot()+theme_bw()
```

## Variance explained

```{r}
tmp2 <- crossGP(geno,samp,phen,prior = "sommer", niter=5,testporc = 0,traits = names(phen)[c(5,7)])
```



## Final plot

```{r}
tmp <- tmp$data[,c("trait","corr")]
tmp2 <- tmp2$data[,c("trait","hrk")]
merG <- merge(tmp,tmp2, by="trait", all=T)
```



```{r}
p <- ggplot(merG, aes(x=trait,y=corr, fill=trait))+geom_boxplot()+theme_bw()+xlab(" ")+
  geom_segment(data=merG,aes(x = as.numeric(as.factor(trait)) - 0.48, 
                                 xend = as.numeric(as.factor(trait)) + 0.48, 
                                 yend = hrk , 
                                 y = hrk ),size=2.5, color="white")+
  geom_segment(data=merG,aes(x = as.numeric(as.factor(trait)) - 0.45, 
                                 xend = as.numeric(as.factor(trait)) + 0.45, 
                                 yend = hrk , 
                                 y = hrk , 
                                 colour = trait),size=1)+
  ylab("Prediction ability")+
  theme(axis.text.x=element_text(angle=80,vjust=0.5))
p

```







